[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openverse-api-client"
dynamic = ["version"]
description = 'Python client for the Openverse API'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "sarayourfriend", email = "24264157+sarayourfriend@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "httpx",
]

[project.optional-dependencies]
generator = [
  "Jinja2",
]

[project.urls]
Documentation = "https://git.sr.ht/~sara/openverse-api-client#readme"
Issues = "https://git.sr.ht/~sara/openverse-api-client/issues"
Source = "https://git.sr.ht/~sara/openverse-api-client"

[project.scripts]
generate-openverse-api-client = "openverse_api_client.generate:generate"

[tool.hatch.version]
path = "src/openverse_api_client/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
features = ["generator"]
[tool.hatch.envs.default.scripts]
generate = "generate-openverse-api-client"
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/openverse_api_client tests}"

[tool.coverage.run]
source_pkgs = ["openverse_api_client", "tests"]
branch = true
parallel = true
omit = [
  "src/openverse_api_client/__about__.py",
]

[tool.coverage.paths]
openverse_api_client = ["src/openverse_api_client", "*/openverse-api-client/src/openverse_api_client"]
tests = ["tests", "*/openverse-api-client/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
