[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[project]
name = "py4pa"
version = "0.1.11"
license = {file = "LICENSE.txt"}
authors = [{name="Kevin Metherell",email = "kevindickens@gmail.com" }]
description = "Package of various helper modules to support various People Analytics projects"
dependencies = [
    "pandas",
    "numpy",
    "datetime",
    "networkx",
    "requests",
    "bs4",
    "urllib3",
    "fake-useragent",
    "pysftp"]
requires-python = ">= 3.6"
readme = "README.md"
classifiers =[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    ]

[project.urls]
Homepage = "https://py4pa.readthedocs.io/en/latest/"
Documentation = "https://py4pa.readthedocs.io/en/latest/"
Repository = "https://github.com/kammetherell/py4pa/"
Issues = "https://github.com/kammetherell/py4pa/issues"


