[tool.poetry]
name = "quranbot-schema-registry"
version = "0.0.27"
description = "quranbot-schema-registry"
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "^4.7.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4"

[tool.pytest.ini_options]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
