---
on:
  push:
    branches: [main, develop]
    paths-ignore:
      # Don't re-build if we only change README.md Or CHANGES.md
      - '**.md'
jobs:
  conda-pkg-build-bw25:
    name: build bw25ui
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-activate-base: true
      - run: |
          conda info
          conda config --set auto_update_conda False
          conda install -y -q conda-libmamba-solver
          conda config --set solver libmamba
          conda install -y -q conda-build anaconda-client
          cd conda.recipe
          yes | anaconda login --username ${{ secrets.ANACONDA_USER }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda config --set anaconda_upload yes
          conda build -c conda-forge -c cmutel -c haasad .
  conda-pkg-build-legacy:
    name: build bw2ui
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-activate-base: true
      - run: |
          conda info
          conda config --set auto_update_conda False
          conda install -y -q conda-libmamba-solver
          conda config --set solver libmamba
          conda install -y -q conda-build anaconda-client
          cd conda.recipe-legacy
          yes | anaconda login --username ${{ secrets.ANACONDA_USER }} --password ${{ secrets.ANACONDA_PASSWORD }}
          conda config --set anaconda_upload yes
          conda build -c conda-forge -c cmutel -c haasad .
