[tool.poetry]
name = "ado_backlog_cli"
version = "0.1.8"
description = "A program to make sense of ADO Backlogs for reports"
authors = ["James Ainslie <your_email@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.1"
azure-devops = "^7.1.0b4"
msrest = "^0.7.1"
tabulate = "^0.9.0"
pytz = "^2024.1"
python-docx = "^1.1.0"
click = "^8.1.7"
pyyaml = "^6.0.1"
pympler = "^1.0.1"
psutil = "^5.9.8"
memory-profiler = "^0.61.0"
termcolor = "^2.4.0"
prettytable = "^3.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
poetry = "^1.8.2"
wheel = "^0.42.0"
setuptools = "^69.1.1"
build = "^1.1.1"
twine = "^5.0.0"

[tool.poetry.scripts]
ado-backlog-cli = "ado_backlog_cli.cli:main"

[[tool.poetry.packages]]
include = "ado_backlog_cli"
from = "src"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
