[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6",
    "numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "sargasso"
version = "0.5.1"
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "numpy>=1.18",
    "pybind11>=2.6",
]

[options]
packages = [
    "sargasso",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = false
