[tool.poetry]
name = "aporacle"
version = "0.0.120"
description = ""
authors = ["Makhosonke Morafo <makhosonke@komokun.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
websockets = "^12.0"
requests = "^2.31.0"
numpy = "^1.26.4"
schedule = "^1.2.1"
pandas = "^2.2.1"
scikit-learn = "^1.4.1.post1"
statsmodels = "^0.14.1"
cachetools = "^5.3.3"
komoutils = "^0.0.214"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"