[tool.poetry]
name = "sonaris"
version = "0.1.4"
description = "Software Framework for Task Automation and Scheduling"
authors = ["dennis <denngohis@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "sonaris", from = "src" }
]
include = ["src/sonaris/assets/**/*"]
[tool.poetry.dependencies]
python = "^3.10,<=3.11.8"
PyQt6 = "^6.6.1"
PyQt6-Charts = "^6.6.0"
numpy = "^1.26.3"
pyqtdarktheme = "^2.1.0"
PyVISA = "^1.14.1"
PyVISA-py = "^0.7.1"
yapf = "^0.40.2"
apscheduler = "^3.10.4"
pyqtgraph = "^0.13.3"
pyyaml = "^6.0.1"
filelock = "^3.13.1"
python-dotenv = {extras = ["cli"], version = "^1.0.1"}
pydantic = "^2.6.3"
colorlog = "^6.8.2"
click = "^8.1.7"
pypiwin32 = "^223"
uvicorn = "^0.28.0"
fastapi = "^0.110.0"
pywin32 = "^306"
docker = "^7.0.0"
zeroconf = "^0.131.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"