[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "osbkca_package"
dynamic = ["version"]
authors = [
    {name = "Osbkca", email="osbkca@gmail.com"}
]
description = "A osbkca package"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.version]
path = "osbkca_package/_version.py"


