[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "notify_sms_py"
version = "1.1.1"
description = "Notify is a bulk SMS Module for sending SMS's accross local zambian phone numbers. It is embedded in [GameBox - Download the app here.]( https://play.google.com/store/apps/details?id=com.microtech.gamebox)"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
keywords = ["sms", "bulk sms", "zambia"]
authors = [{ name = "Patrick Kabwe", email = "patrickckabwe@gmail.com" }]
dependencies = ["requests", 'importlib-metadata; python_version<"3.10"']
requires-python = ">=3.12"

[project.urls]
homepage = "https://github.com/patrickkabwe/notify_sms"
issues = "https://github.com/patrickkabwe/notify_sms/issues"
