[tool.poetry]
name = "pms-trt"
version = "0.1.3"
description = "Package for TensorRT"
authors = ["HyeongSeok Kim <tiryul@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorrt = {version = "8.6.1.post1", source = "nvidia"}
tensorrt-libs = {version = "8.6.1", source = "nvidia"}
tensorrt-bindings = {version = "8.6.1", source = "nvidia"}
cuda-python = "^12.4.0"
loguru = "^0.7.2"
numpy = "^1.26.4"
albumentations = "^1.4.1"


[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com/"
priority = "supplemental"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
